{
 "title": "Gnomes - Overview",
 "tags": [
  "gnome",
  "app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Zarejestrowani użytkownicy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "app_user_count" }
   ]
  },
  {
   "title": "Krasnale (liczba)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "app_gnome_count" }
   ]
  },
  {
   "title": "Budowle (liczba)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "app_building_count" }
   ]
  },
  {
   "title": "Ilość odpowiedzi 4xx (5m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(app_requests_total{status_code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Interakcje - ostatnie 5 minut",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "increase(app_requests_total{route=\"/api/rest/v1/gnomes/interaction\"}[5m])",
     "legendFormat": "interactions"
    }
   ]
  },
  {
   "title": "Ilość odpowiedzi 5xx (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(app_requests_total{status_code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Mapa krasnali",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "gnome",
     "rawSql": "SELECT latitude, longitude, name FROM \"Gnome\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Mapa interakcji",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "gnome",
     "rawSql": "SELECT \"userId\", \"User\".\"name\" AS \"Użytkownik\", \"gnomeId\", \"Gnome\".\"latitude\", \"Gnome\".\"longitude\" FROM \"GnomeInteraction\" INNER JOIN \"Gnome\" ON \"Gnome\".\"id\" = \"GnomeInteraction\".\"gnomeId\" INNER JOIN \"User\" ON \"User\".\"id\" = \"GnomeInteraction\".\"userId\""
    }
   ]
  }
 ]
}